export type SpecialServicesTypes =
  | 'ALCOHOL'
  | 'APPOINTMENT'
  | 'BATTERY'
  | 'COD'
  | 'DANGEROUS_GOODS'
  | 'DRY_ICE'
  | 'PRIORITY_ALERT'
  | 'PRIORITY_ALERT_PLUS'
  | 'NON_STANDARD_CONTAINER'
  | 'PIECE_COUNT_VERIFICATION'
  | 'SIGNATURE_OPTION'
  | 'EVENING'
  | 'DATE_CERTAIN'
  | 'SATURDAY_PICKUP';

